# Generated by Django 4.0.4 on 2024-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo_ID',
            field=models.ImageField(default='https://adonisrecycling.com/wp-content/uploads/2021/06/male-placeholder.jpeg', upload_to=''),
        ),
    ]
