# Generated by Django 4.0.4 on 2024-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0002_student_student_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo_ID_B',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
