# Generated by Django 4.0.4 on 2024-03-31 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0005_student_student_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='https://adonisrecycling.com/wp-content/uploads/2021/06/male-placeholder.jpeg', max_length=200), default=[], size=None),
        ),
    ]
