# Generated by Django 4.0.4 on 2024-04-14 15:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photom', '0006_alter_student_student_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo_ID',
            field=models.ImageField(default='https://adonisrecycling.com/wp-content/uploads/2021/06/male-placeholder.jpeg', upload_to='photo-ids'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='https://adonisrecycling.com/wp-content/uploads/2021/06/male-placeholder.jpeg', max_length=200), blank=True, default=[], null=True, size=None),
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_phone', phonenumber_field.modelfields.PhoneNumberField(default='4155550132', max_length=128, region=None)),
                ('school_name', models.CharField(max_length=200)),
                ('school_position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
