# Generated by Django 4.0.4 on 2024-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0003_student_student_photo_id_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo_ID',
            field=models.FileField(default='https://adonisrecycling.com/wp-content/uploads/2021/06/male-placeholder.jpeg', upload_to=''),
        ),
    ]
