# Generated by Django 4.0.4 on 2024-04-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0009_alter_student_student_photo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_photo_ID_B',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photo_ID',
            field=models.ImageField(default='default-photo-id.PNG', upload_to='photo-ids'),
        ),
    ]
