# Generated by Django 4.0.4 on 2024-04-19 16:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0011_remove_student_student_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_school',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='photom.schoolaccount'),
        ),
        migrations.AlterField(
            model_name='schoolaccount',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolaccount',
            name='school_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='4155550132', max_length=128, region=None),
        ),
    ]
