# Generated by Django 4.0.4 on 2024-04-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0012_class_class_school_alter_schoolaccount_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photom.schoolaccount'),
        ),
    ]
