# Generated by Django 4.0.4 on 2024-04-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0013_alter_class_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_school',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.CASCADE, to='photom.schoolaccount'),
            preserve_default=False,
        ),
    ]
