# Generated by Django 4.0.4 on 2024-04-22 22:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0014_alter_class_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolaccount',
            name='school_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
