# Generated by Django 4.0.4 on 2024-04-22 22:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0015_alter_schoolaccount_school_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolaccount',
            name='school_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
