# Generated by Django 4.0.4 on 2024-05-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0016_alter_schoolaccount_school_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_age',
        ),
    ]
