# Generated by Django 4.0.4 on 2024-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0017_remove_student_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_grade',
            field=models.CharField(max_length=50),
        ),
    ]
