# Generated by Django 4.0.4 on 2024-05-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0018_alter_class_class_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photom.schoolaccount')),
            ],
        ),
    ]
