# Generated by Django 4.0.4 on 2024-05-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0019_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='school_account',
        ),
    ]
