# Generated by Django 4.0.4 on 2024-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0020_remove_photo_school_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
