# Generated by Django 5.0.6 on 2024-05-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0021_notification_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='schoolaccount',
            options={'verbose_name': 'School Account', 'verbose_name_plural': 'School Accounts'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='send_date',
            new_name='date_sent',
        ),
    ]
