# Generated by Django 5.0.6 on 2024-05-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0023_alter_schoolaccount_options_alter_class_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photom.schoolaccount'),
        ),
    ]
