# Generated by Django 5.0.6 on 2024-07-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photom', '0024_alter_class_class_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolaccount',
            name='has_csv',
            field=models.BooleanField(default=False),
        ),
    ]
